version: '2'
services:
    netdata:
        container_name: netdata
        image: netdata/netdata:latest-armhf
        hostname: cube-zero-slave
        ports:
            - 19999:19999
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./netdata.conf:/etc/netdata/netdata.conf:ro
