version: '2'

services:
    portainer:
        container_name: portainer
        image: portainer/portainer:linux-arm-1.20.2
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer-data:/data

volumes:
    portainer-data:
